# These are supported funding model platforms

github: hongping-zh
# ko_fi: # Replace with your Ko-fi username
# open_collective: # Replace with your Open Collective username
# custom: ['https://your-link.com']
